PRIV_DIR=$(MIX_APP_PATH)\priv
NIF_PATH=$(PRIV_DIR)\libfinest.dll
C_SRC=$(MAKEDIR)\c_src

CPPFLAGS=/LD /std:c++17 /W4 /O2 /EHsc
CPPFLAGS=$(CPPFLAGS) /I"$(ERTS_INCLUDE_DIR)" /I"$(FINE_INCLUDE_DIR)"
CPPFLAGS=$(CPPFLAGS) /DFINE_ENABLE_TEST_HOOKS
# We want to eliminate all warnings, so the end user doesn't see any.
CPPFLAGS=$(CPPFLAGS) /WX
CPPFLAGS=$(CPPFLAGS) $(EXTRA_CPPFLAGS)
CPPFLAGS=$(CPPFLAGS) /guard:cf
LDFLAGS=/guard:cf /DYNAMICBASE /NXCOMPAT
LDFLAGS=$(LDFLAGS) $(EXTRA_LDFLAGS)

SOURCES=$(C_SRC)\*.cpp
# We add dependency on Fine header file, since it can change as we test.
FINE_HEADERS=$(FINE_INCLUDE_DIR)\*.hpp

all: $(NIF_PATH)

$(NIF_PATH): $(SOURCES) $(FINE_HEADERS)
	@ if not exist "$(PRIV_DIR)" mkdir "$(PRIV_DIR)"
	cl $(CPPFLAGS) $(SOURCES) /Fe"$(NIF_PATH)" /link $(LDFLAGS)
